# Generated by Django 5.1.2 on 2024-10-10 12:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("obs", models.TextField(blank=True, verbose_name="Observations")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("catalog_date", models.DateTimeField(verbose_name="date published")),
                (
                    "catalog_id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Magic: The Gathering"),
                            (2, "World of Warcraft"),
                            (3, "Yu-Gi-Oh!"),
                            (5, "The Spoils"),
                            (6, "Pokémon"),
                            (7, "Force of Will"),
                            (8, "Cardfight!! Vanguard"),
                            (9, "Final Fantasy"),
                            (10, "Weiss Schwarz"),
                            (11, "Dragon Borne"),
                            (12, "My Little Pony"),
                            (13, "Dragon Ball"),
                            (15, "Star Wars: Destiny"),
                            (16, "Flesh and Blood"),
                            (17, "Digimon"),
                            (18, "One Piece"),
                            (19, "Lorcana"),
                            (20, "Battle Spirits Saga"),
                            (21, "Star Wars Unlimited"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "catalog_type",
                    models.PositiveSmallIntegerField(choices=[(1, "Products"), (2, "Prices")]),
                ),
                (
                    "md5sum",
                    models.CharField(max_length=32, unique=True, verbose_name="MD5sum"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MTGCard",
            fields=[
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("obs", models.TextField(blank=True, verbose_name="Observations")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "cm_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(null=True, unique=True, verbose_name=255)),
                ("category_id", models.PositiveIntegerField(default=1)),
                ("expansion_id", models.PositiveIntegerField()),
                ("metacard_id", models.PositiveIntegerField()),
                (
                    "cm_date_added",
                    models.DateTimeField(verbose_name="Date added to cardmarket"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["cm_id"], name="idx_mtgcard_cm_id")],
            },
        ),
        migrations.CreateModel(
            name="MTGCardPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("obs", models.TextField(blank=True, verbose_name="Observations")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("catalog_date", models.DateTimeField(verbose_name="Catalog Date")),
                ("cm_id", models.IntegerField(verbose_name="cardmarket id")),
                ("avg", models.FloatField(null=True, verbose_name="Average price")),
                ("low", models.FloatField(null=True, verbose_name="Low price")),
                ("trend", models.FloatField(null=True, verbose_name="Trend price")),
                (
                    "avg1",
                    models.FloatField(null=True, verbose_name="Average price for 1 day"),
                ),
                (
                    "avg7",
                    models.FloatField(null=True, verbose_name="Average price for 7 days"),
                ),
                (
                    "avg30",
                    models.FloatField(null=True, verbose_name="Average price for 30 days"),
                ),
                (
                    "avg_foil",
                    models.FloatField(null=True, verbose_name="Foil average price"),
                ),
                (
                    "low_foil",
                    models.FloatField(null=True, verbose_name="Foil low price"),
                ),
                (
                    "trend_foil",
                    models.FloatField(null=True, verbose_name="Foil trend price"),
                ),
                (
                    "avg1_foil",
                    models.FloatField(null=True, verbose_name="Foil average price for 1 day"),
                ),
                (
                    "avg7_foil",
                    models.FloatField(null=True, verbose_name="Foil average price for 7 days"),
                ),
                (
                    "avg30_foil",
                    models.FloatField(null=True, verbose_name="Foil average price for 30 days"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="prices.mtgcard",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["cm_id"], name="idx_mtgprice_cm_id")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog_date", "cm_id"),
                        name="Unique card price per day",
                    )
                ],
            },
        ),
    ]
