# Generated by Django 5.2 on 2026-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0008_reduced_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mtgcardprice",
            name="prices_mtgc_card_id_572283_idx",
        ),
        migrations.AddIndex(
            model_name="mtgcardprice",
            index=models.Index(
                fields=["card", "catalog_date", "trend"],
                name="prices_mtgc_card_id_4447c0_idx",
            ),
        ),
    ]
