# Generated by Django 5.2 on 2026-05-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0010_remove_mtgcardprice_unique_card_price_per_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtgcardprice",
            name="card",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="prices.mtgcard",
            ),
        ),
    ]
