# Generated by Django 5.1.2 on 2024-10-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTGSet",
            fields=[
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("obs", models.TextField(blank=True, verbose_name="Observations")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "expansion_id",
                    models.PositiveSmallIntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Cardmarket Set ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Set Name"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="mtgcard",
            name="expansion_id",
        ),
        migrations.AlterField(
            model_name="mtgcard",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mtgcard",
            name="expansion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="prices.mtgset",
            ),
        ),
    ]
