# Generated by Django 5.1.2 on 2024-11-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0004_price_slopes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mtgcardpriceslope",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="mtgcardprice",
            index=models.Index(fields=["catalog_date"], name="idx_mtgprice_catalog_date"),
        ),
        migrations.AddIndex(
            model_name="mtgcardprice",
            index=models.Index(fields=["cm_id", "catalog_date"], name="idx_mtgprice_cm_id_date"),
        ),
        migrations.AddIndex(
            model_name="mtgcardprice",
            index=models.Index(fields=["low"], name="idx_mtgprice_low"),
        ),
        migrations.AddIndex(
            model_name="mtgcardpriceslope",
            index=models.Index(fields=["card"], name="idx_slope_card"),
        ),
        migrations.AddIndex(
            model_name="mtgcardpriceslope",
            index=models.Index(fields=["interval_days"], name="idx_slope_interval"),
        ),
        migrations.AddIndex(
            model_name="mtgcardpriceslope",
            index=models.Index(fields=["card", "interval_days"], name="idx_slope_card_interval"),
        ),
        migrations.AddConstraint(
            model_name="mtgcardpriceslope",
            constraint=models.UniqueConstraint(fields=("card", "interval_days"), name="unique_card_interval"),
        ),
    ]
