# Generated by Django 5.2 on 2026-03-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0007_add_prices"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mtgcard",
            name="idx_mtgcard_cm_id",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardprice",
            name="idx_mtgprice_cm_id",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardprice",
            name="idx_mtgprice_catalog_date",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardprice",
            name="idx_mtgprice_cm_id_date",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardprice",
            name="idx_mtgprice_low",
        ),
    ]
