# Generated by Django 5.2 on 2026-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0009_improve_index"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mtgcardprice",
            name="Unique card price per day",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardprice",
            name="prices_mtgc_card_id_4447c0_idx",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardpriceslope",
            name="idx_slope_card",
        ),
        migrations.RemoveIndex(
            model_name="mtgcardpriceslope",
            name="idx_slope_card_interval",
        ),
        migrations.AddIndex(
            model_name="mtgcardprice",
            index=models.Index(fields=["card", "catalog_date"], name="idx_price_card_date"),
        ),
        migrations.AddIndex(
            model_name="mtgcardprice",
            index=models.Index(fields=["catalog_date", "trend"], name="idx_price_date_trend"),
        ),
        migrations.AddIndex(
            model_name="mtgcardpriceslope",
            index=models.Index(
                fields=["interval_days", "percent_change"],
                name="idx_slope_interval_change",
            ),
        ),
        migrations.AddConstraint(
            model_name="mtgcardprice",
            constraint=models.UniqueConstraint(fields=("catalog_date", "cm_id"), name="unique_card_price_per_day"),
        ),
    ]
