# Generated by Django 5.2 on 2026-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0011_alter_mtgcardprice_card"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mtgcard",
            index=models.Index(fields=["metacard_id", "cm_id"], name="idx_card_meta_cm"),
        ),
    ]
