# Generated by Django 5.1.2 on 2024-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScryfallCard",
            fields=[
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update at"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("obs", models.TextField(blank=True, verbose_name="Observations")),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("cardmarket_id", models.PositiveIntegerField()),
                ("oracle_id", models.CharField(max_length=128, null=True)),
                ("name", models.CharField(max_length=256, null=True)),
                ("mana_cost", models.CharField(blank=True, max_length=128, null=True)),
                ("cmc", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("types", models.CharField(blank=True, max_length=256, null=True)),
                ("subtypes", models.CharField(blank=True, max_length=256, null=True)),
                ("colors", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "color_identity",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "oracle_text",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("legalities", models.CharField(blank=True, max_length=256, null=True)),
                ("image_small", models.URLField(blank=True, null=True)),
                ("image_normal", models.URLField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["cardmarket_id"], name="idx_scryfallcard_cm_id")],
            },
        ),
    ]
