# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main, staging ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Validate_and_Test:
    runs-on: ubuntu-latest

    permissions:
      statuses: write
      checks: write
      contents: read  # More restrictive than 'write'
      pull-requests: write

    steps:
    - uses: actions/checkout@v5  # Updated from v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Cache pip
      uses: actions/cache@v4  # Updated from v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set-up Requirements
      if: steps.cache.outputs.cache-hit != 'true'  # Uncommented this line
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: upterm
#      uses: lhotari/action-upterm@v1

#    - name: Run migrations
#      run: |
#        cd src
#        ./manage.py migrate

#    - name: Set-up Scripts
#      run: |
#        git submodule init
#        git submodule update
#        ./scripts/get_static_validation_backend.sh

    - name: Static Validation
      run: |
        ./scripts/static_validate_ci_backend.sh

    - name: Test Reporter
      uses: dorny/test-reporter@v1
      if: always()  # Changed from 'success() || failure()' - cleaner syntax
      with:
        name: Report - Static Validation
        path: report_*.xml
        reporter: java-junit
        fail-on-error: false  # Added this to prevent build failure if no reports